version: 1
module_version: 0.1.3
runner_image: spacelift/runner:latest

test_defaults:
  before_init:
    - "terraform fmt -check"
    - "tflint"
    - "git-chglog -o CHANGELOG.md"
    - "terraform validate"
    - "tfsec"
tests:  
  - name: default