version: 1
module_version: 0.1.3
runner_image: spacelift/runner:latest

test_defaults:
  before_init:
    - "curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash"
    - "tflint --init && tflint"
    - "git-chglog -o CHANGELOG.md"
    - "terraform validate"
tests:  
  - name: default