version: 1
module_version: 0.1.3
runner_image: spacelift/runner:latest

test_defaults:
  before_init:
    - "terraform init"
    - "mkdir -p ./bin"
    - "curl -L -o ./bin/tflint.zip https://github.com/terraform-linters/tflint/releases/download/v0.53.0/tflint_linux_amd64.zip"
    - "unzip -o ./bin/tflint.zip -d ./bin"
    - "chmod +x ./bin/tflint"
    - "export PATH=$PATH:./bin"
    - "./bin/tflint --init && ./bin/tflint"
    - "terraform validate"
tests:
  - name: default
