repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
      - id: detect-private-key
      - id: end-of-file-fixer

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.1
    hooks:
    - id: terraform_fmt
    - id: terraform_tflint
      args:
        - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
    - id: terraform_validate
      args:
        - --hook-config=--retry-once-with-cleanup=true
    # - id: terraform_checkov
    - id: terraform_docs
      args:
        - --hook-config=--path-to-file=README.MD
        - --hook-config=--add-to-existing-file=true
        - --hook-config=--create-file-if-not-exist=true
        - --hook-config=--use-standard-markers=true
        - '--args=--config=.terraform-docs.yml'
