name: release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
          RELEASE_NAME_PREFIX: "Release: "
          ALLOW_EMPTY_CHANGELOG: true
  slackNotification:
    name: Terraform-Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        with:
          node-version: '20'
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_CHANNEL: iac-guild
          SLACK_USERNAME: github-actions
          SLACK_TITLE: Terraform-AWS-Grafana Tag & Release